FROM alpine:latest
ARG HASKORD_PATH
ARG MUEVAL_PATH
ARG MUEVAL_CORE_PATH
ARG CONFIG_PATH
RUN apk update
RUN apk add gmp ncurses libc6-compat
COPY $HASKORD_PATH /
COPY $MUEVAL_PATH /bin
COPY $MUEVAL_CORE_PATH /bin
COPY $CONFIG_PATH /
CMD ./haskord
