name:                haskord
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/haskord#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- readme.org

dependencies:
  - base >= 4.7 && < 5
  - websockets
  - req
  - aeson
  - wuss
  - text
  - scientific
  - bytestring
  - yaml
  - time
  - stm
  - async
  - vector
  - unordered-containers
  - pretty-simple
  - safe-exceptions
  - mtl
  - req
  - http-api-data
  - streaming
  - brick
  - vty
  - singletons
  - persistent
  - persistent-sqlite
  - persistent-template
  - resource-pool
  - monad-logger
  - megaparsec
  - network-uri
  - hashable
  - haxl

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - PartialTypeSignatures
  - RecordWildCards
library:
  source-dirs: src
  ghc-options:      -O2 -Wall

executables:
  haskord:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      -O2 -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - haskord
      - hint
      - mueval
      - show
      - process
