name:                haskord-bot
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/saevarb/haskord/haskord-bot#readme
license:             BSD3
author:              Sævar berg 
maintainer:          example@example.com
copyright:           2018 Sævar Berg
category:            Web
extra-source-files:
- readme.org

default-extensions:
  - RecordWildCards
  - DataKinds
  - BangPatterns
  - ConstraintKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
  - PartialTypeSignatures

executables:
  haskord:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      -O2 -threaded -rtsopts -with-rtsopts=-N -Wall
    dependencies:
      - base >= 4.7 && < 5
      - haskord
      - haskord-plugin-resources
      - haskord-plugin-eval
